name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: "https://registry.npmjs.org"

      - name: 自动生成版本号 & CHANGELOG
        uses: google-github-actions/release-please-action@v3
        id: release_please
        with:
          release-type: "node"
          package-name: "karin-plugin-ba"
          bump-minor-pre-major: true
          include-v-in-tag: true

      - name: 发布到 npm
        if: ${{ steps.release_please.outputs.release_created }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 创建 GitHub Release
        if: ${{ steps.release_please.outputs.release_created }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_please.outputs.tag_name }}
          body: ${{ steps.release_please.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}